/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ActiveDirectory */

#ifndef _Included_ActiveDirectory
#define _Included_ActiveDirectory
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     ActiveDirectory
	 * Method:    testt
	 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_ActiveDirectory_testt
	(JNIEnv*, jobject, jstring, jstring);

	/*
	 * Class:     ActiveDirectory
	 * Method:    getname
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_ActiveDirectory_getname
	(JNIEnv*, jobject, jstring);

	/*
	 * Class:     ActiveDirectory
	 * Method:    getP
	 * Signature: (Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_ActiveDirectory_getP
	(JNIEnv*, jobject, jstring);

	/*
	 * Class:     ActiveDirectory
	 * Method:    passWordLastSet
	 * Signature: (Ljava/lang/String;)J
	 */
	JNIEXPORT jlong JNICALL Java_ActiveDirectory_passWordLastSet
	(JNIEnv*, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
